# Generated by Django 5.2.3 on 2025-07-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
